import React from 'react';

function PrivatePolicy(props) {
  return (
    <div className="container mx-auto">
      <div className="content w-2/3 mx-auto p-1 lg:p-5">
        <h2 className="text-gray-300 font-medium mb-4 text-xl lg:text-3xl text-center">Private Policy</h2>
        <div className="text-gray-300 lg:text-base text-sm">
          <p>FshareTV (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by FshareTV.</p>
          <div className="space my-2 lg:my-5">
          </div>
          <p>This Privacy Policy applies to our website, FshareTV, and its associated subdomains (collectively, our “Service”) alongside our application, FshareTV. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p>
          <div className="space my-2 lg:my-5">
          </div>
          <h3 className="text-gray-300 font-medium my-4 text-xl lg:text-3xl">Meanings</h3>
          <p>For this Privacy Policy:</p>
          <div className="space my-2 lg:my-5">
          </div>
          <ul className="list-disc list-inside">
            <li>You is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ,</li>
            <li>Website is referred to FshareTV, accessible from FshareTV</li>
            <li>
             Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            </li>
            <li>
              Third-party Social Media Service could be any website or social network website in which a User can log in or create an account to use the Service.
            </li>
            <li>
              Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.
            </li>
            <li>
             Usage Data it’s referred to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the website.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default PrivatePolicy;